export const SPREADSHEET_FIELDS = [
  "Entry Type",
  "Entry Name",
  "SID",
  "Quantity",
  "Unit",
  "Min Level",
  "Price",
  "Value",
  "Notes",
  "Tags",
  "Product Link",
  "Primary Folder",
  "Subfolder-level1",
  "Subfolder-level2",
  "Subfolder-level3",
  "Subfolder-level4",
  "Photo1",
] as const;
